<?php


/**
 * Implements hook_permission
 */
function rsc_util_permission() {
  $ret = array();

  //admin
  $ret['Use RSC utilities'] = array(
    'title' => t('Use RSC utilities')
  );

  return $ret;
}


/**
 * Implements hook_menu
 */
function rsc_util_menu() {

  /* FILES */

  $items['admin/config/media/rsc_util/files'] = array(
    'title'            => 'RSC Utilities: Files',
    'description'      => "Miscellaneous utilities to manipulate files.",
    'page callback'    => 'rsc_util_pages_files',
    'file'             => 'rsc_util.pages.inc',
    'access arguments' => array('Use RSC utilities'),
  );

  $items['admin/config/media/rsc_util/files/help'] = array(
    'title'            => 'RSC Utilities: Files',
    'type'             => MENU_DEFAULT_LOCAL_TASK,
    'weight'           => -100,
  );

  $items['admin/config/media/rsc_util/files/missing'] = array(
    'title'            => 'Missing files',
    'description'      => 'View file fields (a.k.a. attachments) for which one or more files are missing (i.e. not present on the file system).',
    'page callback'    => 'rsc_util_pages_missing_files',
    'file'             => 'rsc_util.pages.inc',
    'access arguments' => array('Use RSC utilities'),
    'type'             => MENU_LOCAL_TASK,
  );

  $items['admin/config/media/rsc_util/files/suggest'] = array(
    'title'            => 'Missing files - suggestions',
    'description'      => 'Try to find suggested matches for missing files based on file names',
    'page callback'    => 'drupal_get_form',
    'page arguments'   => array('rsc_util_forms_missing_files_suggestion'),
    'file'             => 'rsc_util.forms.inc',
    'access arguments' => array('Use RSC utilities'),
    'type'             => MENU_LOCAL_TASK,
  );

  $items['admin/config/media/rsc_util/files/unmanaged'] = array(
    'title'            => 'Unmanaged files',
    'description'      => 'View files that are present on the filesystem, but are not referenced by a node.',
    'page callback'    => 'rsc_util_pages_unmanaged_files',
    'file'             => 'rsc_util.pages.inc',
    'access arguments' => array('Use RSC utilities'),
    'type'             => MENU_LOCAL_TASK,
  );

  $items['admin/config/media/rsc_util/files/unmanaged/%'] = array(
    'title'            => 'Unmanaged files',
    'description'      => 'View files that are present on the filesystem, but are not referenced by a node.',
    'page callback'    => 'rsc_util_pages_unmanaged_files',
    'page arguments'   => array(5),
    'file'             => 'rsc_util.pages.inc',
    'access arguments' => array('Use RSC utilities'),
  );

  return $items;
}
